
const statenames = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'NewHampshire',
    'NewJersey',
    'NewMexico',
    'NewYork',
    'NorthCarolina',
    'NorthDakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'RhodeIsland',
    'SouthCarolina',
    'SouthDakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'WestVirginia',
    'Wisconsin',
    'Wyoming'
]

var scales = {
    Alabama : true,
    Alaska : true,
    Arizona : true,
    Arkansas : true,
    California : true,
    Colorado : true,
    Connecticut : true,
    Delaware : true,
    Florida : true,
    Georgia : true,
    Hawaii : true,
    Idaho : true,
    Illinois : true,
    Indiana : true,
    Iowa : true,
    Kansas : true,
    Kentucky : true,
    Louisiana : true,
    Maine : true,
    Maryland : true,
    Massachusetts : true,
    Michigan : true,
    Minnesota : true,
    Mississippi : true,
    Missouri : true,
    Montana : true,
    Nebraska : true,
    Nevada : true,
    NewHampshire : true,
    NewJersey : true,
    NewMexico : true,
    NewYork : true,
    NorthCarolina : true,
    NorthDakota : true,
    Ohio : true,
    Oklahoma : true,
    Oregon : true,
    Pennsylvania : true,
    RhodeIsland : true,
    SouthCarolina : true,
    SouthDakota : true,
    Tennessee : true,
    Texas : true,
    Utah : true,
    Vermont : true,
    Virginia : true,
    Washington : true,
    WestVirginia : true,
    Wisconsin : true,
    Wyoming : true
}

const statehood = {
    'Alabama' : 1819,
    'Alaska' : '1959 (1)',
    'Arizona' : '1912 (2)', 
    'Arkansas' : 1836,
    'California' : 1850,
    'Colorado' : 1876,
    'Connecticut' : '1788 (2)',
    'Delaware' : '1787 (1)',
    'Florida' : '1845 (1)',
    'Georgia' : '1788 (1)',
    'Hawaii' : '1959 (2)',
    'Idaho' : '1890 (1)',
    'Illinois' : 1818,
    'Indiana' : 1816,
    'Iowa' : 1846,
    'Kansas' : 1861,
    'Kentucky' : 1792,
    'Louisiana' : 1812,
    'Maine' : 1820,
    'Maryland' : '1788 (4)',
    'Massachusetts' : '1788 (3)',
    'Michigan' : 1837,
    'Minnesota' : 1858,
    'Mississippi' : 1817,
    'Missouri' : 1821,
    'Montana' : '1889 (3)',
    'Nebraska' : 1867,
    'Nevada' : 1864, 
    'NewHampshire' : '1788 (6)',
    'NewJersey' : '1787 (3)',
    'NewMexico' : '1912 (1)',
    'NewYork' : '1788 (8)',
    'NorthCarolina' : 1789,
    'NorthDakota' : '1889 (1/2)',
    'Ohio' : 1803,
    'Oklahoma' : 1907,
    'Oregon' : 1859,
    'Pennsylvania' : '1787 (2)',
    'RhodeIsland' : 1790,
    'SouthCarolina' : '1788 (5)',
    'SouthDakota' : '1889 (1/2)',
    'Tennessee' : 1796,
    'Texas' : '1845 (2)',
    'Utah' : 1896,
    'Vermont' : 1791,
    'Virginia' : '1788 (7)',
    'Washington' : '1889 (4)',
    'WestVirginia' : 1863,
    'Wisconsin' : 1848,
    'Wyoming' : '1890 (2)'    
}

//Durstenfeld shuffle
//Source: https://stackoverflow.com/a/12646864
function ShuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array
}

export { ShuffleArray, statenames, statehood, scales }